/*
 / _____)             _              | |
( (____  _____ ____ _| |_ _____  ____| |__
 \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 _____) ) ____| | | || |_| ____( (___| | | |
(______/|_____)_|_|_| \__)_____)\____)_| |_|
    (C)2015 Semtech

Description: End device comissioning parameters

License: Revised BSD License, see LICENSE.TXT file include in the project

Maintainer: Miguel Luis and Gregory Cristian
*/
#ifndef __LORA_COMISSIONING_H__
#define __LORA_COMISSIONING_H__

// see random.org

// OverTheAir Activation
/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 */
#define IEEE_OUI                                    0x70, 0xB3, 0xD5  // von Gesys

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */

#define STATIC_DEVICE_EUI   0
const uint8_t  LORAWAN_DEVICE_EUI[8] =   { IEEE_OUI, 0xFF, 0xFE, 0x29, 0x71, 0x0F }; // 0x70B3D5FFFE297xxx von Gesys used when STATIC_DEVICE_EUI 1

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
/*!
 * Application IEEE EUI (big endian)
 */
const uint8_t LORAWAN_APPLICATION_EUI[8] =  { IEEE_OUI, 0xFF, 0xFE, 0x29, 0x70, 0x24 }; // 0x70B3D5FFFE297023 von Gesys  0x24 for TFB Datalogger

/*!
 * AES encryption/decryption cipher application key
 */

const uint8_t LORAWAN_APPLICATION_KEY[16] = { 0xB0, 0xBC, 0x44, 0x79, 0xB5, 0xDA, 0x40, 0x65, 0x93, 0x36, 0xEE, 0xC0, 0x9A, 0xEF, 0x19, 0x91 }; // B0BC4479B5DA40659336EEC09AEF1991


// DeviceActivationByPersonalization
/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0
/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value
 */
#define STATIC_DEVICE_ADDRESS 0
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x19900722 // used when STATIC_DEVICE_ADDRESS 1
/*!
 * AES encryption/decryption cipher network session key
 */
const uint8_t LORAWAN_NWKSKEY[16] = { 0x29, 0x6F, 0x95, 0x8A, 0x9D, 0xBB, 0x45, 0x09, 0x84, 0x57, 0x0F, 0x8F, 0x48, 0x0E, 0x76, 0x4C }; //296F958A9DBB450984570F8F480E764C
/*!
 * AES encryption/decryption cipher application session key
 */
const uint8_t LORAWAN_APPSKEY[16] = { 0xC1, 0xF3, 0x26, 0x86, 0x24, 0xBC, 0x42, 0x00, 0x8C, 0x29, 0x35, 0xD7, 0x64, 0x3D, 0xCE, 0x4E }; // C1F3268624BC42008C2935D7643DCE4E



// Broadcast
#define LORAWAN_BROADCAST_ADDRESS                      ( uint32_t )0
/*!
 * AES encryption/decryption cipher network session key
 */
const uint8_t LORAWAN_BC_NWKSKEY[16] = { 0x57, 0x93, 0x13, 0xE3, 0x6A, 0x33, 0x4D, 0xB5, 0xBB, 0xFE, 0xF2, 0x08, 0xB7, 0xDD, 0x87, 0x32 }; // 579313E36A334DB5BBFEF208B7DD8732
 
/*!
 * AES encryption/decryption cipher application session key
 */
const uint8_t LORAWAN_BC_APPSKEY[16] = { 0x29, 0x70, 0x12, 0xCF, 0x9C, 0x14, 0x44, 0x12, 0xAF, 0xFF, 0xA6, 0xDD, 0x8E, 0x0B, 0xD5, 0xE7 }; // 297012CF9C144412AFFFA6DD8E0BD5E7



#endif // __LORA_COMISSIONING_H__
